import{a as p,S as f,i as c}from"./assets/vendor-1AYLTIiv.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const g="https://pixabay.com/api/",h="50282223-5a409711ad86c04843247122a";function l(r){return p.get(g,{params:{key:h,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(o=>o.data.hits)}l("pictures").then(r=>{console.log(r)});const u=document.querySelector(".gallery"),a=document.querySelector(".loader"),y=new f(".gallery a",{captionsData:"alt",captionDelay:250});function L(r){const o=r.map(({webformatURL:i,largeImageURL:n,tags:e,likes:t,views:s,comments:d,downloads:m})=>`<li class="gallery-item">
            <a href="${n}">
              <img src="${i}" alt="${e}" />
            </a>
            <div class="info">
              <p><b>Likes:</b> ${t}</p>
              <p><b>Views:</b> ${s}</p>
              <p><b>Comments:</b> ${d}</p>
              <p><b>Downloads:</b> ${m}</p>
            </div>
        </li>`).join("");u.innerHTML=o,y.refresh()}function b(){u.innerHTML=""}function S(){console.log("run: show loader"),a.classList.add("is-active"),a.classList.remove("is-hidden")}function v(){a.classList.add("is-hidden"),a.classList.remove("is-active")}const w=document.querySelector(".form");w.addEventListener("submit",P);function P(r){r.preventDefault();const o=r.target.elements["search-text"].value.trim();if(o===""){c.warning({message:"Please enter a search term!",position:"topRight"});return}b(),S(),l(o).then(i=>{if(i.length===0){c.error({message:"Sorry, there are no images matching your search query. Please, try again!",position:"topRight"});return}L(i)}).catch(i=>{console.error(i),c.error({message:"Something went wrong. Please try again later.",position:"topCenter"})}).finally(()=>{v()}),r.target.reset()}
//# sourceMappingURL=index.js.map
